### ISSUE TITLE
Chore: Add automation tests for other Operative Systems

### ISSUE THREAD

**Issue by airvzxf** [Col-E/InstrumentationServer#10]
Add automation tests for other operating systems: Windows and possible macOS. The reason is given by some file IO for self-extraction. It'd be nice as a fail-safe against regressions.

In my experience, I propose this solution for the workflows in Github Actions: first run in parallel the build and unit tests for all the target O.S. If it passes, then run the build / release which actually exists. At the end, if the CI workflow is complete, it display the results for the unit test.

![ColE-InstrumentationServer-Workflow-MultiOS](https://user-images.githubusercontent.com/831380/229333910-32476d5f-43f8-4fa2-93a5-a0ee9db300dc.png)

**Comment by airvzxf** [comment]
Hi, @Col-E.

I am working on these enhancements. At this point, I need to check with you some technical decisions, but first let me present what we have until now.

Changes:
- I created a dummy pull request to execute the actions. You can see the changes and the actions here: https://github.com/airvzxf/InstrumentationServer/pull/3.
- I create a matrix for 3 OS and 10 Java versions, which run 30 jobs in parallel, usually they take 4–5 minutes.
  - If you want to specify what OS or Java versions, I can modify.
  - os: [ ubuntu-latest, windows-latest, macos-latest ]
  - java-version: [ 8, 11, 12, 13, 14, 15, 16, 17, 18, 19 ]
- I kept all one workflow file (build.yml), and deleted the other. The reason is to create a continued pipeline. In GitHub, all the jobs need to be in one file; otherwise, it can be used the `workflow_run` but it breaks the flow in the diagram. In GitLab, it is possible to have different files and have the flow of the pipeline without problems.
  - I changed the chained jobs, as I proposed in my first comment.
  - The flow of the pipeline or workflow with my changes, it look like that:
  - ![GitHub action pipeline with dependencies](https://user-images.githubusercontent.com/831380/229352315-62ef1b7e-9a93-4e18-9737-963287440a3b.png)
- I removed the condition about the manual run with `workflow_dispatch`. I improved with a menu, if the user or maintainer selects the manual execution of the CI, then it is possible to execute for release. Furthermore, it can select the O.S. and the Java version. I'll provide evidence:
  - ![GitHub action run manual with menu](https://user-images.githubusercontent.com/831380/229352581-5123b241-3881-4f09-bcc6-85c8208e2c7a.png)
  - ![GitHub action run manual with menu selected](https://user-images.githubusercontent.com/831380/229352605-689fdbfb-a6a5-4faf-bb41-b91f6e57ab91.png)
- If some user creates a pull request to master or push to master, it will be executed only the `Test Multi-SO`. To execute the release job, it needs to follow these conditions:
  - The job: Test multi-OS execute successfully.
  - The action was executed manually and the option `Do you want to release?` was selected.
  - The repository where the GitHub action is executing is `Col-E/InstrumentationServer`. It prevents to release from other repositories.
  - The branch is referring to `refs/heads/master`.
- In the `build`/release job, if the tag for project version does not exist, or it has a problem, then it interrupts the job, preventing running the subsequent jobs: `event_file` and `unit-test-results`.
- I removed the conditions about `github.event_name == 'workflow_dispatch'` and `steps.tagged.outputs.tagExists == 0`. But ultimately, the workflow is working as the previous logic, I only removed the logic to one control point and preventing to continuing if the conditions are not passed.

Technical questions:
- It is about the unit test results. The `build` job has the step `Upload Test Results` with `actions/upload-artifact@v2.3.1`. It archives the artifacts. Then in the `unit-test-results` job, it publishes the results.
  - That I noticed is the upload test results in `build` always is executed `if: always()` but not always is publishing the results.
  - With my logic, I removed this path. Currently, upload only happens if the release is in progress. The question is… do we need to upload the test results for any execution of the GitHub action of the CI workflow?

**Comment by Col-E** [comment]
>matrix for 3 OS and 10 Java versions

Generally, I think the JDK versions to test against would be:

- `8` for the minimum supported version
- `11` _(maybe?)_ for testing the jump from pre-9 non-modularity to post-9 modularity. We don't currently have any behavior that should be affected currently, but later down the road it may be useful.
- `<latest-jvm>` for testing that the server works on whatever is the latest release. If there are breaking API changes in the JDK this should let us know early on.
    - If '`latest` isn't easily specified we can set it to `19` and then increment it whenever a new JDK is released.

> To execute the release job, it needs to follow these conditions:

I was scrolling through the PR and wondered about those changes. Good catch 👍 

*******

> The question is… do we need to upload the test results for any execution of the GitHub action of the CI workflow?

Realistically, probably not. The most valuable information in diagnosing problems with failing tests in the CI is the log output in the action itself. The test result XML files themselves are not typically super important. 

> Currently, upload only happens if the release is in progress. 

This however, I would say is counter-intuitive.  Information about test failures should not be bound to wanting to make a release.

**Comment by airvzxf** [comment]
> Generally, I think the JDK versions to test against would be:
> 
>    * `8` for the minimum supported version
> 
>    * `11` _(maybe?)_ for testing the jump from pre-9 non-modularity to post-9 modularity. We don't currently have any behavior that should be affected currently, but later down the road it may be useful.
> 
>    * `<latest-jvm>` for testing that the server works on whatever is the latest release. If there are breaking API changes in the JDK this should let us know early on.
>       
>      * If '`latest` isn't easily specified we can set it to `19` and then increment it whenever a new JDK is released.

---

Firstly, I changed the `distribution` from `adopt-hotspot` to `temurin`. Furthermore, the `temurin` recognizes the JDK 20. This is the reason:

https://github.com/actions/setup-java#supported-distributions

> NOTE: AdoptOpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt and adopt-openj9, to temurin and semeru respectively, to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).

Secondly, the latest version was possible to get from the Adoptium API, then pass to the `test-multiple-os` job.

Thirdly, the Java versions are as follows: 8, 11, latest.

If you want to review the workflow, check this https://github.com/airvzxf/InstrumentationServer/actions/runs/4592555949

![GitHub actions CI](https://user-images.githubusercontent.com/831380/229405450-9db92cb8-e19e-4107-b96b-acbe1cfd144a.png)

The changes can be viewed on: https://github.com/airvzxf/InstrumentationServer/pull/3

**Comment by airvzxf** [comment]
> > The question is… do we need to upload the test results for any execution of the GitHub action of the CI workflow?
> 
> Realistically, probably not. The most valuable information in diagnosing problems with failing tests in the CI is the log output in the action itself. The test result XML files themselves are not typically super important.
> 
> > Currently, upload only happens if the release is in progress.
> 
> This however, I would say is counter-intuitive. Information about test failures should not be bound to wanting to make a release.

Given the new architecture and all the modifications, in this case, it would make more sense for me to have everything related to test inside `test-multi-os`. Such as the test itself, creating the artifacts and uploading the artifacts and publishing the test results. What do you think?

I have another quick question, the latest job `unit-test-results`, is it publishing the results on GitHub or is it publishing in another place. Or is it used in the JReleaser?

**Comment by Col-E** [comment]
> I have another quick question

`unit-test-results` [publishes to GitHub, such as replying to PR's](https://github.com/Col-E/InstrumentationServer/pull/9#issuecomment-1492671816)

> Given the new architecture and all the modifications, in this case, it would make more sense for me to have everything related to test inside `test-multi-os`. Such as the test itself, creating the artifacts and uploading the artifacts and publishing the test results. What do you think?

As long as publishing doesn't result in one notification per matrix entry that should be fine.

For instance, lets say there are 5 tests, 1 fails.

- The current setup that runs on one OS/JVM will post only one comment: _"5 tests ran, 1 failed"_
- For a setup with multiple OS/JVM combinations, it would be awkward to receive multiple duplicate comments from the github bot
    - Ideally, the test results are managed in such a way that there is still only one comment, but it combines the results together

**Comment by airvzxf** [comment]
> As long as publishing doesn't result in one notification per matrix entry that should be fine.
> 
> For instance, lets say there are 5 tests, 1 fails.
> 
>   * The current setup that runs on one OS/JVM will post only one comment: _"5 tests ran, 1 failed"_
> 
>   * For a setup with multiple OS/JVM combinations, it would be awkward to receive multiple duplicate comments from the github bot
>       
>     * Ideally, the test results are managed in such a way that there is still only one comment, but it combines the results together

---

Done as requested. The test bot takes all the tests and adds in one summary. Only if an error exists, it will show in what environment and file is the error.

In pull request:

![Test result bot in pull request](https://user-images.githubusercontent.com/831380/229437408-a7c87164-1e9e-4088-a7f0-8a61b563e319.png)

In workflow summary:

![Test result bot in workflow summary](https://user-images.githubusercontent.com/831380/229437527-66c749a6-1b9d-4023-a6be-75df6c916bb6.png)

As job in the summary:

![Test result bot as job in the summary](https://user-images.githubusercontent.com/831380/229437747-5c9372ff-8321-4e44-b9af-fa57df490d69.png)

The pipeline or workflow looks like it:

![workflow](https://user-images.githubusercontent.com/831380/229438065-df5813a3-ce43-4843-8e4d-92bfbaa934ce.png)

**Comment by airvzxf** [comment]
With that being all, if you have any other comments, they are welcome. Otherwise, kindly let me know, so I can make the pull request to your repository.

**Comment by Col-E** [comment]
That looks excellent, I don't think I have any additional comments here

**Comment by Col-E** [comment]
Done as of #11

**Comment by airvzxf** [comment]
I noticed in the actions of your repository when is a pull request from me, it didn't show the table result of the Unit Test (https://github.com/Col-E/InstrumentationServer/actions/runs/4594246832), but if you merged, it showed (https://github.com/Col-E/InstrumentationServer/actions/runs/4594763674). I don't know if it is because the changes to the CI/CD workflow weren't in master. Let's see for next pull requests what happens.

Warning triggered via pull request from me.

![Warning pull request on workflow](https://user-images.githubusercontent.com/831380/229464670-e59bc884-8367-44e7-84b6-fdf3260c513d.png)

Not warning triggered on master commit.

![Not warning on master commit](https://user-images.githubusercontent.com/831380/229464829-0b0f3405-e850-4010-b575-7f284a8e2a00.png)

**Comment by Col-E** [comment]
> I don't know if it is because the changes to the CI/CD workflow weren't in master. 

Seems like a likely cause.

> Let's see for next pull requests what happens.

👍
