### ISSUE TITLE
Suggestion: Provide Pre-Compiled JARs for Multiple Java Versions in Releases

### ISSUE THREAD

**Issue by lanvent** [Col-E/InstrumentationServer#12]
Thank you for developing such a fantastic Java agent. I have found it to be extremely useful, especially in my work with Recaf.

I've noticed that the releases currently only include JAR files compiled with Java 17. While the library appears to be compatible with Java 8 and 11, it does require manual recompilation using the corresponding JDK to make it compatible with the target jar's Java version. 
Would it be possible to also include JAR files compiled for Java 8 and Java 11 in future releases? This would make it easier to integrate the agent into projects running on these versions without requiring manual recompilation.

**Comment by Col-E** [comment]
The latest release is built for Java 8 though. I've confirmed this by looking at the github and maven releases. Where are you getting issues stating the lib is using a newer version of the class file format?

**Comment by lanvent** [comment]
I saw this configuration setting in the MANIFEST.MF file of the latest release.

```
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 17
Agent-Class: software.coley.instrument.Agent
Can-Redefine-Classes: true
Can-Retransform-Classes: true
Premain-Class: software.coley.instrument.Agent
```

**Comment by Col-E** [comment]
You can build with a newer jdk and target older bytecode. You can use a variety of tools to validate the files indeed use Java 8.

**Comment by lanvent** [comment]
Thank you for your prompt response on my previous issue. I appreciate the clarification about being able to build with a newer JDK and target older bytecode.

However, I can reproduce an issue when using the release version of the agent to attach in java8 env. Here's a simple Java class I used for testing:

```java
public class A {
    public static void main(String[] args) {
        String str = "\"test\"";
        System.out.println(str);
        System.out.println(str);
        while(true){

        }
    }
}
```

**Case 1: Using the agent compiled with Java 8**

Log:

```
D:\project\IDEA\test\test>set path=C:\Users\lanvent\.jdks\liberica-1.8.0_382\bin;
D:\project\IDEA\test\test>set JAVA_HOME=C:\Users\lanvent\.jdks\liberica-1.8.0_382;
D:\project\IDEA\test\test>javac A.java
D:\project\IDEA\test\test>java -javaagent:D:\project\InstrumentationServer\target\instrumentation-server-1.3.6.jar A
"test"
"test"
<Use Recaf to connect>
```

No issues encountered. Recaf can connect successfully.

**Case 2: Using the agent from the latest release (compiled with Java 17)**

Log:

```
D:\project\IDEA\test\test>set path=C:\Users\lanvent\.jdks\liberica-1.8.0_382\bin;
D:\project\IDEA\test\test>set JAVA_HOME=C:\Users\lanvent\.jdks\liberica-1.8.0_382;
D:\project\IDEA\test\test>javac A.java
D:\project\IDEA\test\test>java -javaagent:D:\reverse\instrumentation-server-1.3.6.jar A
"test"
"test"
<Use Recaf to connect>
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at software.coley.instrument.io.ByteBufferDataInput.readUTF(ByteBufferDataInput.java:124)
        at software.coley.instrument.message.request.RequestClassMessage.lambda$static$0(RequestClassMessage.java:13)
        at software.coley.instrument.io.codec.StructureCodec$1.decode(StructureCodec.java:15)
        at software.coley.instrument.sock.ChannelHandler.readLoop(ChannelHandler.java:172)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

As you can see, the second case throws a `NoSuchMethodError`, specifically with the ByteBuffer class, which is only available from Java 9 onwards. This error occurs when I try to connect via Recaf.

This discrepancy between the two cases might suggest that the Java 17 compiled agent isn't fully backward-compatible with Java 8 as expected. Could you please look into this?

Thank you!

**Comment by Col-E** [comment]
Damn, I swear we fixed those.  Its been brought up in the past. They changed some locations of where method definitions occur, its a specific thing that I'm surprised they let slip by :/

**Comment by Col-E** [comment]
I'll make a new release tomorrow to address this since that's a bug

**Comment by Col-E** [comment]
Pushed _"tomorrow"_ a bit back after discovering a few other bugs. This has been solved, working on some new issues. Release 1.4.0 will be out soon though.

**Comment by lanvent** [comment]
thanks, really happy to see it getting better.
