### ISSUE TITLE
Figure out why the 'LiveTest' does not work on GitHub CI, but runs locally

### ISSUE THREAD

**Issue by Col-E** [Col-E/InstrumentationServer#8]
Title. Using Java 8-17, the LiveTest works fine locally, but not on CI for some reason.

**Comment by airvzxf** [comment]
Fixed in the Pull Request #9. I added some notes.

---

**Note:**
- Could someone download my changes and tell me if it is working on Windows? https://github.com/airvzxf/InstrumentationServer/tree/bug-ci-broken-live-test.
- If you want to check the pipeline passing the Live Test, please refer to this pipeline: https://github.com/airvzxf/InstrumentationServer/actions/runs/4579270217/jobs/8086854281.
- The pipeline is broken or red because the release job is breaking in my repository and branch because they are not master.

**Comment by Col-E** [comment]
> Could someone download my changes and tell me if it is working on Windows?

Will do 👍 

> The pipeline is broken or red because the release job is breaking in my repository 

I didn't anticipate this failure. A fork doesn't copy over the git tags, so it will _always_ attempt to make a release since it will do so automatically when the project version isn't a tag.

I made it this way so releasing is just a matter of bumping the version and pushing, all automatic. But I see that's gonna cause issues for contributors on forks, so I'll have to rework that.

**Comment by Col-E** [comment]
Resolved: Partially me being a dumb-ass, accidentally committing local changes I didn't mean to, and API differences between 8/9+ per linked issues mentioned in #9 

Thanks again for checking this out so quickly 👍

**Comment by airvzxf** [comment]
> I didn't anticipate this failure. A fork doesn't copy over the git tags, so it will _always_ attempt to make a release since it will do so automatically when the project version isn't a tag.
> 
> I made it this way so releasing is just a matter of bumping the version and pushing, all automatic. But I see that's gonna cause issues for contributors on forks, so I'll have to rework that.

@Col-E 

I can work in this feature or spec, I would add conditions to check it it is master and tags. If you agree, let me know and I create a new issue, then a pull request.

**Comment by Col-E** [comment]
Already done 👍 

The artifact _should_ be published to maven central in addition to JitPack now.

**Comment by airvzxf** [comment]
@Col-E ,

I want to add a GitHub Actions to check the O.S. Windows and Mac to run the CI and the Unit Tests. If you are agree, let me know and I'll create an issue and then the pull request.

**Comment by Col-E** [comment]
On that front, go for it. Only point of concern would be making sure things like the `Release` job don't get triggered once per OS in the matrix.

**Comment by airvzxf** [comment]
> On that front, go for it. Only point of concern would be making sure things like the `Release` job don't get triggered once per OS in the matrix.

Yes, I'll take special attention to it. I am tented to only release for the Ubuntu that you have in your set up.

**Comment by airvzxf** [comment]
I was working on it, but then I thought that it is not necessary because of Java. I don't need to compile and check if it works in different S.O., it should be work in all of these O.S… If you think it is necessary, please, let me know and I'll start to work on it.

**Comment by Col-E** [comment]
Typically I don't think Java needs multi OS CI, but given this does some file IO for self-extraction, it wouldn't hurt in this specific case. Now that it works on CI and locally it _should_ be fine. I don't intend on touching the IO logic. But it'd be nice as a fail-safe against regressions.

**Comment by airvzxf** [comment]
> Typically I don't think Java needs multi OS CI, but given this does some file IO for self-extraction, it wouldn't hurt in this specific case. Now that it works on CI and locally it _should_ be fine. I don't intend on touching the IO logic. But it'd be nice as a fail-safe against regressions.

Perfect, I'll work on it.
